[package]
name = "wl-termshot"
description = "Wayland Terminal Screenshotter"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
cursive = { version = "0.21.1", features = ["toml"] }
